spring.application.name=blackjack
server.port=3000
spring data.mongodb.uri=mongodb://localhost:27017/blackjackdb
spring.r2dbc.url=r2dbc:mariadb://localhost:3306/blackjackdb
spring.r2dbc.username=devs
spring.r2dbc.password=pw1234
